#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * DIY_Prusa_Mini_Conditionals.h
 * Configuration logic based on DIY_Prusa_Mini_Configuration.h options at compile time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define DIY_PRUSA_MINI_VERSION 20241019

//===========================================================================
//============================ Source Code Info =============================
//===========================================================================

#define SOURCE_CODE_URL "bit.ly/426zdX1"
#define WEBSITE_URL SOURCE_CODE_URL

//===========================================================================
//============================== Printer Name ===============================
//===========================================================================

#ifndef DIY_PRUSA_MINI_CUSTOM_PRINTER_NAME
  #define DIY_PRUSA_MINI_CUSTOM_PRINTER_NAME "Mini"
#endif

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

// Define MOTHERBOARD here so preflight-checks.py works
#if ENABLED(DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0
#elif ENABLED(DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0_1
#elif ENABLED(DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

// Default Extruder inverting
#if ENABLED(DIY_PRUSA_MINI_EXTRUDER_STOCK)
  #define DIY_PRUSA_MINI_INVERT_E0_DIR false
#elif ENABLED(DIY_PRUSA_MINI_EXTRUDER_BONDTECH_IFS)
  #define DIY_PRUSA_MINI_INVERT_E0_DIR true
#endif

// User Extruder Inverting
#if ENABLED(DIY_PRUSA_MINI_INVERT_E_DIR)
  #if DIY_PRUSA_MINI_INVERT_E0_DIR == true
    #undef DIY_PRUSA_MINI_INVERT_E0_DIR  // Prevent redefined warnings
    #define DIY_PRUSA_MINI_INVERT_E0_DIR false
  #elif DIY_PRUSA_MINI_INVERT_E0_DIR == false
    #undef DIY_PRUSA_MINI_INVERT_E0_DIR  // Prevent redefined warnings
    #define DIY_PRUSA_MINI_INVERT_E0_DIR true
  #endif
#endif

#if ENABLED(DIY_PRUSA_MINI_EXTRUDER_STOCK)
  #define DIY_PRUSA_MINI_EXTRUDER_STEPS_PER_UNIT  325
#elif ENABLED(DIY_PRUSA_MINI_EXTRUDER_BONDTECH_IFS)
  #define DIY_PRUSA_MINI_EXTRUDER_STEPS_PER_UNIT  415
#endif

#define DIY_PRUSA_MINI_DEFAULT_AXIS_STEPS_PER_UNIT  { 100, 100, 400, (DIY_PRUSA_MINI_EXTRUDER_STEPS_PER_UNIT) }

// StallGuard settings
#ifndef DIY_PRUSA_MINI_X_STALL_SENSITIVITY
  #define DIY_PRUSA_MINI_X_STALL_SENSITIVITY 75
#endif
#ifndef DIY_PRUSA_MINI_Y_STALL_SENSITIVITY
  #define DIY_PRUSA_MINI_Y_STALL_SENSITIVITY 75
#endif

// Homing speeds (mm/min)
#ifndef DIY_PRUSA_MINI_HOMING_FEEDRATE_MM_M
  #define DIY_PRUSA_MINI_HOMING_FEEDRATE_MM_M { (50*60), (50*60), (6*60) }
#endif

// X inverting
#if ENABLED(DIY_PRUSA_MINI_INVERT_X_DIR)
  #define DIY_PRUSA_MINI_INVERT_X_DIR true
#else // Stock
  #define DIY_PRUSA_MINI_INVERT_X_DIR false
#endif

// Y inverting
#if ENABLED(DIY_PRUSA_MINI_INVERT_Y_DIR)
  #define DIY_PRUSA_MINI_INVERT_Y_DIR true
#else // Stock
  #define DIY_PRUSA_MINI_INVERT_Y_DIR false
#endif

// Z inverting
#if ENABLED(DIY_PRUSA_MINI_INVERT_Z_DIR)
  #define DIY_PRUSA_MINI_INVERT_Z_DIR false
#else // Stock
  #define DIY_PRUSA_MINI_INVERT_Z_DIR true
#endif

//===========================================================================
//============================== Input Shaping ==============================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_INPUT_SHAPING)
  #define INPUT_SHAPING_X
  #define INPUT_SHAPING_Y
#else
  #define S_CURVE_ACCELERATION // Not needed/recommended with Input Shaping
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

#ifndef DIY_PRUSA_MINI_NOZZLE_TO_PROBE_OFFSET
  #define DIY_PRUSA_MINI_NOZZLE_TO_PROBE_OFFSET { -29, -3, -0.4 }
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#define NO_VARIANCE_MONITOR_WARNING // Suppress THERMAL_PROTECTION_VARIANCE_MONITOR warning

#if ENABLED(DIY_PRUSA_MINI_THERMISTOR_STOCK_SEMITEC_104NT)
  #define DIY_PRUSA_MINI_TEMP_SENSOR_0      5
#elif ENABLED(DIY_PRUSA_MINI_THERMISTOR_GENERIC_100K)
  #define DIY_PRUSA_MINI_TEMP_SENSOR_0      1
#endif

#if ENABLED(DIY_PRUSA_MINI_HOTEND_MPCTEMP)
  #define MPCTEMP

  #if DISABLED(DIY_PRUSA_MINI_CUSTOM_HOTEND_MPCTEMP)
    #define DIY_PRUSA_MINI_CUSTOM_MPC_HEATER_POWER              { 40.0f }
    #define DIY_PRUSA_MINI_CUSTOM_MPC_BLOCK_HEAT_CAPACITY       { 10.46f }
    #define DIY_PRUSA_MINI_CUSTOM_MPC_SENSOR_RESPONSIVENESS     { 0.7801f }
    #define DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF        { 0.0564f }
    #define DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 { 0.1264f }
    #define DIY_PRUSA_MINI_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM  { 5.6e-3f }
  #endif
#else
  #define PIDTEMP

  #if DISABLED(DIY_PRUSA_MINI_CUSTOM_HOTEND_PID)
    #define DIY_PRUSA_MINI_DEFAULT_Kp   7.00 // 21.80
    #define DIY_PRUSA_MINI_DEFAULT_Ki   0.50 // 2.75
    #define DIY_PRUSA_MINI_DEFAULT_Kd  45.00 // 43.30
  #endif
#endif

#if DISABLED(DIY_PRUSA_MINI_CUSTOM_BED_PID)
  #define DIY_PRUSA_MINI_DEFAULT_bedKp  120.00 // 36.80
  #define DIY_PRUSA_MINI_DEFAULT_bedKi    1.50 // 2.72
  #define DIY_PRUSA_MINI_DEFAULT_bedKd  600.00 // 332.40
#endif

//===========================================================================
//================================== Fans ===================================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_PART_COOLING_FAN_GENERIC)
  #define DIY_PRUSA_MINI_FAN_MIN_PWM 0
#elif ENABLED(DIY_PRUSA_MINI_PART_COOLING_FAN_24V_DELTA_BFB0524HH)
  #define DIY_PRUSA_MINI_FAN_MIN_PWM 20
#elif ENABLED(DIY_PRUSA_MINI_PART_COOLING_FAN_24V_SOUNDORIGINAL)
  #define DIY_PRUSA_MINI_FAN_MIN_PWM 50 // 26
#endif

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_BED_LEVELING_BILINEAR)
  #define AUTO_BED_LEVELING_BILINEAR
  #define G29_RETRY_AND_RECOVER
#elif ENABLED(DIY_PRUSA_MINI_BED_LEVELING_UBL)
  #define AUTO_BED_LEVELING_UBL
  #define MESH_EDIT_GFX_OVERLAY
#endif

//===========================================================================
//============================== Custom Menus ===============================
//===========================================================================

// Sheet Profiles Menu
#if ENABLED(DIY_PRUSA_MINI_SHEET_PROFILES_MENU)
  #define CUSTOM_MENU_CONFIG

  #if defined(DIY_PRUSA_MINI_SHEET_1_DESC) && defined(DIY_PRUSA_MINI_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_DESC DIY_PRUSA_MINI_SHEET_1_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_2_DESC) && defined(DIY_PRUSA_MINI_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_DESC DIY_PRUSA_MINI_SHEET_2_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_3_DESC) && defined(DIY_PRUSA_MINI_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_DESC DIY_PRUSA_MINI_SHEET_3_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_4_DESC) && defined(DIY_PRUSA_MINI_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_DESC DIY_PRUSA_MINI_SHEET_4_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_5_DESC) && defined(DIY_PRUSA_MINI_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_DESC DIY_PRUSA_MINI_SHEET_5_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_6_DESC) && defined(DIY_PRUSA_MINI_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_DESC DIY_PRUSA_MINI_SHEET_6_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_7_DESC) && defined(DIY_PRUSA_MINI_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_DESC DIY_PRUSA_MINI_SHEET_7_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_8_DESC) && defined(DIY_PRUSA_MINI_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_DESC DIY_PRUSA_MINI_SHEET_8_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_9_DESC) && defined(DIY_PRUSA_MINI_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_DESC DIY_PRUSA_MINI_SHEET_9_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_CONFIRM
  #endif

  #if defined(DIY_PRUSA_MINI_SHEET_10_DESC) && defined(DIY_PRUSA_MINI_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_DESC DIY_PRUSA_MINI_SHEET_10_DESC ": "  STRINGIFY(DIY_PRUSA_MINI_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_GCODE "M851 Z" STRINGIFY(DIY_PRUSA_MINI_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_CONFIRM
  #endif
#endif

// Calibration Menu
#if ENABLED(DIY_PRUSA_MINI_CALIBRATION_MENU)
  #define CUSTOM_MENU_MAIN
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_REVERSE_ENCODER_DIRECTION)
  #define REVERSE_ENCODER_DIRECTION
#endif
