#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * DIY_Prusa_Mini_SanityCheck.h
 * Validate DIY_Prusa_Mini_Configuration.h options at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define DIY_PRUSA_MINI_VERSION 20241019

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

#if MANY(DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
  #error "Only one DIY_PRUSA_MINI_MOTHERBOARD option can be enabled at a time."
#elif NONE(DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, DIY_PRUSA_MINI_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
  #error "Invalid DIY_PRUSA_MINI_MOTHERBOARD option."
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

#if DISABLED(DIY_PRUSA_MINI_E_STEPPER_LDO_1_8)
  #error "Invalid DIY_PRUSA_MINI_E_STEPPER option."
#endif
#if DISABLED(DIY_PRUSA_MINI_XY_STEPPERS_LDO_1_8)
  #error "Invalid DIY_PRUSA_MINI_XY_STEPPERS option."
#endif
#if DISABLED(DIY_PRUSA_MINI_Z_STEPPER_LDO_1_8)
  #error "Invalid DIY_PRUSA_MINI_Z_STEPPER option."
#endif

//===========================================================================
//============================== Input Shaping ==============================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_INPUT_SHAPING)
  #ifndef DIY_PRUSA_MINI_SHAPING_FREQ_X
    #error "DIY_PRUSA_MINI_SHAPING_FREQ_X is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_SHAPING_FREQ_Y
    #error "DIY_PRUSA_MINI_SHAPING_FREQ_Y is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_SHAPING_ZETA_X
    #error "DIY_PRUSA_MINI_SHAPING_ZETA_X is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_SHAPING_ZETA_Y
    #error "DIY_PRUSA_MINI_SHAPING_ZETA_Y is invalid or not defined."
  #endif
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

#if ALL(DIY_PRUSA_MINI_EXTRUDER_STOCK, DIY_PRUSA_MINI_EXTRUDER_BONDTECH_IFS)
  #error "Only one DIY_PRUSA_MINI_EXTRUDER option can be enabled at a time."
#elif NONE(DIY_PRUSA_MINI_EXTRUDER_STOCK, DIY_PRUSA_MINI_EXTRUDER_BONDTECH_IFS)
  #error "Invalid DIY_PRUSA_MINI_EXTRUDER option."
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#if ALL(DIY_PRUSA_MINI_THERMISTOR_STOCK_SEMITEC_104NT, DIY_PRUSA_MINI_THERMISTOR_GENERIC_100K)
  #error "Only one DIY_PRUSA_MINI_THERMISTOR option can be enabled at a time."
#elif NONE(DIY_PRUSA_MINI_THERMISTOR_STOCK_SEMITEC_104NT, DIY_PRUSA_MINI_THERMISTOR_GENERIC_100K)
  #error "Invalid DIY_PRUSA_MINI_THERMISTOR option."
#endif

#if ENABLED(DIY_PRUSA_MINI_CUSTOM_HOTEND_PID)
  #ifndef DIY_PRUSA_MINI_DEFAULT_Kp
    #error "DIY_PRUSA_MINI_DEFAULT_Kp is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_DEFAULT_Ki
    #error "DIY_PRUSA_MINI_DEFAULT_Ki is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_DEFAULT_Kd
    #error "DIY_PRUSA_MINI_DEFAULT_Kd is invalid or not defined."
  #endif
#endif

#if ENABLED(DIY_PRUSA_MINI_CUSTOM_BED_PID)
  #ifndef DIY_PRUSA_MINI_DEFAULT_bedKp
    #error "DIY_PRUSA_MINI_DEFAULT_bedKp is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_DEFAULT_bedKi
    #error "DIY_PRUSA_MINI_DEFAULT_bedKi is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_DEFAULT_bedKd
    #error "DIY_PRUSA_MINI_DEFAULT_bedKd is invalid or not defined."
  #endif
#endif

#if ALL(DIY_PRUSA_MINI_HOTEND_MPCTEMP, DIY_PRUSA_MINI_CUSTOM_HOTEND_PID)
  #error "DIY_PRUSA_MINI_HOTEND_MPCTEMP and DIY_PRUSA_MINI_CUSTOM_HOTEND_PID cannot be enabled at the same time."
#endif

#if ENABLED(DIY_PRUSA_MINI_CUSTOM_HOTEND_MPCTEMP)
  #if DISABLED(DIY_PRUSA_MINI_HOTEND_MPCTEMP)
    #error "DIY_PRUSA_MINI_CUSTOM_HOTEND_MPCTEMP requires DIY_PRUSA_MINI_HOTEND_MPCTEMP."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_MPC_HEATER_POWER
    #error "DIY_PRUSA_MINI_CUSTOM_MPC_HEATER_POWER is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_MPC_BLOCK_HEAT_CAPACITY
    #error "DIY_PRUSA_MINI_CUSTOM_MPC_BLOCK_HEAT_CAPACITY is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_MPC_SENSOR_RESPONSIVENESS
    #error "DIY_PRUSA_MINI_CUSTOM_MPC_SENSOR_RESPONSIVENESS is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF
    #error "DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255
    #error "DIY_PRUSA_MINI_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 is invalid or not defined."
  #endif
  #ifndef DIY_PRUSA_MINI_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM
    #error "DIY_PRUSA_MINI_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM is invalid or not defined."
  #endif
#endif

//===========================================================================
//============================ Part Cooling Fan =============================
//===========================================================================

#if MANY(DIY_PRUSA_MINI_PART_COOLING_FAN_GENERIC, DIY_PRUSA_MINI_PART_COOLING_FAN_24V_DELTA_BFB0524HH, DIY_PRUSA_MINI_PART_COOLING_FAN_24V_SOUNDORIGINAL)
  #error "Only one DIY_PRUSA_MINI_PART_COOLING_FAN option can be enabled at a time."
#elif NONE(DIY_PRUSA_MINI_PART_COOLING_FAN_GENERIC, DIY_PRUSA_MINI_PART_COOLING_FAN_24V_DELTA_BFB0524HH, DIY_PRUSA_MINI_PART_COOLING_FAN_24V_SOUNDORIGINAL)
  #error "Invalid DIY_PRUSA_MINI_PART_COOLING_FAN option."
#endif

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

#if ALL(DIY_PRUSA_MINI_BED_LEVELING_BILINEAR, DIY_PRUSA_MINI_BED_LEVELING_UBL)
  #error "Only one DIY_PRUSA_MINI_BED_LEVELING option can be enabled at a time."
#elif NONE(DIY_PRUSA_MINI_BED_LEVELING_BILINEAR, DIY_PRUSA_MINI_BED_LEVELING_UBL)
  #error "Invalid DIY_PRUSA_MINI_BED_LEVELING option."
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if DISABLED(DIY_PRUSA_MINI_DISPLAY_BTT_TFT35_E3_TFT)
  #error "Invalid DIY_PRUSA_MINI_DISPLAY option."
#endif

#ifndef DIY_PRUSA_MINI_LCD_LANGUAGE
  #error "Invalid DIY_PRUSA_MINI_LCD_LANGUAGE option."
#endif

//===========================================================================
//=========================== Sheet Profiles Menu ===========================
//===========================================================================

#if ENABLED(DIY_PRUSA_MINI_SHEET_PROFILES_MENU)
  // Description is enabled, but no offset
  #if defined(DIY_PRUSA_MINI_SHEET_1_DESC) && !defined(DIY_PRUSA_MINI_SHEET_1_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_1_OFFSET is required when DIY_PRUSA_MINI_SHEET_1_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_2_DESC) && !defined(DIY_PRUSA_MINI_SHEET_2_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_2_OFFSET is required when DIY_PRUSA_MINI_SHEET_2_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_3_DESC) && !defined(DIY_PRUSA_MINI_SHEET_3_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_3_OFFSET is required when DIY_PRUSA_MINI_SHEET_3_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_4_DESC) && !defined(DIY_PRUSA_MINI_SHEET_4_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_4_OFFSET is required when DIY_PRUSA_MINI_SHEET_4_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_5_DESC) && !defined(DIY_PRUSA_MINI_SHEET_5_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_5_OFFSET is required when DIY_PRUSA_MINI_SHEET_5_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_6_DESC) && !defined(DIY_PRUSA_MINI_SHEET_6_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_6_OFFSET is required when DIY_PRUSA_MINI_SHEET_6_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_7_DESC) && !defined(DIY_PRUSA_MINI_SHEET_7_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_7_OFFSET is required when DIY_PRUSA_MINI_SHEET_7_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_8_DESC) && !defined(DIY_PRUSA_MINI_SHEET_8_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_8_OFFSET is required when DIY_PRUSA_MINI_SHEET_8_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_9_DESC) && !defined(DIY_PRUSA_MINI_SHEET_9_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_9_OFFSET is required when DIY_PRUSA_MINI_SHEET_9_DESC is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_10_DESC) && !defined(DIY_PRUSA_MINI_SHEET_10_OFFSET)
    #error "DIY_PRUSA_MINI_SHEET_10_OFFSET is required when DIY_PRUSA_MINI_SHEET_10_DESC is enabled."
  #endif

  // Offset is enabled, but no description
  #if defined(DIY_PRUSA_MINI_SHEET_1_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_1_DESC)
    #error "DIY_PRUSA_MINI_SHEET_1_DESC is required when DIY_PRUSA_MINI_SHEET_1_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_2_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_2_DESC)
    #error "DIY_PRUSA_MINI_SHEET_2_DESC is required when DIY_PRUSA_MINI_SHEET_2_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_3_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_3_DESC)
    #error "DIY_PRUSA_MINI_SHEET_3_DESC is required when DIY_PRUSA_MINI_SHEET_3_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_4_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_4_DESC)
    #error "DIY_PRUSA_MINI_SHEET_4_DESC is required when DIY_PRUSA_MINI_SHEET_4_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_5_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_5_DESC)
    #error "DIY_PRUSA_MINI_SHEET_5_DESC is required when DIY_PRUSA_MINI_SHEET_5_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_6_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_6_DESC)
    #error "DIY_PRUSA_MINI_SHEET_6_DESC is required when DIY_PRUSA_MINI_SHEET_6_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_7_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_7_DESC)
    #error "DIY_PRUSA_MINI_SHEET_7_DESC is required when DIY_PRUSA_MINI_SHEET_7_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_8_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_8_DESC)
    #error "DIY_PRUSA_MINI_SHEET_8_DESC is required when DIY_PRUSA_MINI_SHEET_8_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_9_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_9_DESC)
    #error "DIY_PRUSA_MINI_SHEET_9_DESC is required when DIY_PRUSA_MINI_SHEET_9_OFFSET is enabled."
  #elif defined(DIY_PRUSA_MINI_SHEET_10_OFFSET) && !defined(DIY_PRUSA_MINI_SHEET_10_DESC)
    #error "DIY_PRUSA_MINI_SHEET_10_DESC is required when DIY_PRUSA_MINI_SHEET_10_OFFSET is enabled."
  #endif
#endif
